### ISSUE TITLE
Nested blocks

### ISSUE THREAD

**Issue by pilif0** [pilif0/basilisk#15]
If we regard a block of statements as a statement in itself, they can naturally be nested. This would allow better management of scope as well as prepare for implementation of conditional statements and loops.

## Tasks:
- [ ] Adjust grammar to consider a block of statements as a statement
- [ ] Add AST node type `Block` containing a set of statements to reflect this
- [ ] Generate code from this node type by pushing a scope on the named values stack, executing the statements in sequence and popping the scope
